### ISSUE TITLE
Use protocol relative urls for image assets

### ISSUE THREAD

**Issue by mikelkew** [cpradio/discourse-plugin-imgflip#6]
Would be great if the urls for the images returned from the API were either fixed to be https only, or perhaps protocol relative. This would prevent serving mixed content on discourse installs using ssl.

ImgFlip seems to support https requests to its images, so am hoping this should be an easy fix.

**Comment by cpradio** [comment]
I'm confused, this already can use the https API, it is a site setting. Search for imgflip in Admin > Settings

Or are you saying that ImgFlip is returning HTTP image URLs? Ah, I see it is. In my opinion this should be fixed by ImgFlip. If HTTPS is requested, it should be returning HTTPS.

**Comment by mikelkew** [comment]
Yeah, am referring to the urls returned by ImgFlip. I agree, it really should be something fixed by them. Fairly easy to strip out the protocol from URLs in the response, but would certainly expect it to be that way already in the API.

I guess it's not a huge problem for now, because once a user picks an image, a local copy is made anyway, which will then use a https image url in the thread. The only time there will be mixed content is in the image browser.

Thanks, I'll see how I go requesting a change to the response from ImgFlip.

**Comment by cpradio** [comment]
Yeah, let me know. If they refuse to do anything I can look into doing it, I just really hate altering returned content from a third party as it shouldn't be the responsibility of the calling app to do so.

**Comment by cpradio** [comment]
I see that ImgFlip is now returning https in their responses, can you confirm you are seeing that too?

**Comment by mikelkew** [comment]
Yep, I'm seeing that too. Sent a request to them just after my last comment. I didn't get a response from them, but looks like it prompted them to work on it. Thanks for looking into it!
